name: game_for_cats_2025
description: Game For Cats
publish_to: 'none'
version: 3.3.0+33

environment:
  sdk: ^3.8.1


dependencies:
  flame: ^1.30.1
  flame_audio: ^2.11.8
  go_router: ^14.1.0
  image_picker: ^1.0.7
  provider: ^6.1.2
  shared_preferences: ^2.2.2
  freezed_annotation: ^2.4.4
  flutter_localizations:
    sdk: flutter
  flutter:
    sdk: flutter 
  intl: ^0.20.2
  path_provider: ^2.1.5
  sqflite: ^2.4.2
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.6
  flutter_gen_runner: ^5.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.12
  freezed: ^2.5.7

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21

flutter_native_splash:
    color: "#ffffff" # Splash ekranının arka plan rengi
    image: assets/images/splashscreen.png # Splash ekranı için logo
    android: true
    ios: true
    web: false
    fullscreen: true

flutter:   
  generate: true
  uses-material-design: true
  assets: 
    - assets/images/
    - assets/audio/
